# .gitlab-ci.yml
stages:
  - build
  - test
  - deploy

# Build stage
build:
  stage: build
  script:
    - echo "Building the project..."

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    
  only:
    - main  # deploy only when committing to the main branch
